name: test

on:
  - workflow_dispatch
  - push

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    name: Foundry Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-0dc266dd8e645b932ef43551f0dd9dc4e9769528
        id: init

      - name: Run Forge fmt src
        run: |
          forge fmt --check ./src
        id: fmt_src
        if: ${{ steps.init.conclusion == 'success' }}

      - name: Run Forge fmt test
        run: |
          forge fmt --check ./test
        id: fmt_test
        if: ${{ steps.init.conclusion == 'success' }}

      - name: Run Forge fmt test
        run: |
          forge fmt --check ./deploy
        id: fmt_deploy
        if: ${{ steps.init.conclusion == 'success' }}
  test:
    name: Foundry Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
